### PR TITLE
Fix #181

### LINKED ISSUE #181: Mass output of "QFile::open: File (/path/to/file) already open"
I've compiled locally off hash 6f5eaa808c6ed209d74f765babf09ca24d22e06b

After opening glogg from command line, I see 100s of the Qt error message over the course of a couple hours.

I'm using search with extended regexp, following file, and the file is being written to but not moved or anything. There is no observable behaviour problem.

### PR DESCRIPTION
**Pull request by gin-ahirsch**
This moves the allocation of the `LogDataOperation` slightly down, since we now only enqueue the operation conditionally.

### CODE REVIEW

**Comment by Lightjohn** [comment]
I am now running that branch as my normal build but it's crashing on verbose logging.
It happens systematically when I follow the output and enable the search for pattern (no regex, only multiple words). If you need more information I can run in debug mode or something like that.

**Comment by Lightjohn** [comment]
That's strange it's systematic for me:
The error in debug mode (-dddd):
`*** Error in ./glogg: corrupted size vs. prev_size: 0x- `

The heapdump from `-d`: 
[heap.log](https://github.com/nickbnf/glogg/files/2123051/heap.log)

The error from -dddd is not here every time.

I'm on Ubuntu 16.04 default qt5-dev libs.

**Comment by gin-ahirsch** [comment]
It seems `seek()`ing the closed file fails and it eventually crashes. I've changed the fix to open in a new  `QFile` and only use it if opening is successful. Otherwise it keeps the previously opened file.

**Comment by gin-ahirsch** [comment]
@nickbnf Do I need to lock `fileMutex_` to modify the `attached_file_`?

**Comment by Lightjohn** [comment]
It's no more crashing on my side.
I don't know what was the goal of that fix, but there is still a corner case (that I know is painful):
If the folder containing the logs is deleted and re created with the logs, this version does not see the new one.
I don't think it's in the scope of that fix but I wanted you to know that case.

**Comment by gin-ahirsch** [comment]
Yeah, that'd be considered a different file. I think the watcher works in terms of inodes, not filenames. It should behave the same as `tail -f` I think.

**Comment by Lightjohn** [comment]
Exactly, that was my guess, but these branch is already a big improvement
for my daily workflow :) Thanks

**Comment by nickbnf** [comment]
@gin-ahirsch, yes we should lock fileMutex_ everytime we touch attached_file_ (it was mainly done to maintain the atomicity of each seek-read sequence). I don't really see what could go wrong if we do not here but it should.

I don't see why this change would fix @Lightjohn's issue #151. And yes I know it does but I just can't see why, any idea?

**Comment by gin-ahirsch** [comment]
@Lightjohn had issues with `seek()` being called on a closed file. Perhaps this sometimes just returned messed up contents instead of causing a crash? Compiling with address-sanitizer indicates problems in `src/compressedlinestorage.cpp` which disappears with this change.
Possibly the inotify implementation could also be improved so that we only get a signal when we can actually open the changed file? I mean there can still be "races" if we change and immediately after delete the file, the inotify-signal gets sent in-between those two actions and glogg reacts after the deletion has occurred. But this isn't even the case I tested, I just edited the file and saved the changes.

**Comment by nickbnf** [comment]
Thanks @gin-ahirsch, I've committed a similar fix in 9f850936f193b6e0057829e50d76cbf76e3a62c7 that uses a heuristic to re-open the file only when needed, it should fix @Lightjohn's problem too without causing extra processing in the common case of an appended file.

**Pull request closed without merging**
