### PR TITLE
Additional encodings

### PR DESCRIPTION
**Pull request by Seeraeuber**
Added additional encodings as requested in issue #217. Please review my changes in detail as this is my first contribution :)
I didn't touch the encoding speculator too much, as 8 bit encodings are too hard to guess...

### CODE REVIEW

**Comment by Seeraeuber** [comment]
And sorry for the commit mess... I spent hours on uploading my actual changes, including overwriting my local files with the master branch :man_facepalming:

**Comment by z33ky** [comment]
You can `git reset --soft master && git commit` to squash the commits into a single one.

**Comment by nickbnf** [comment]
Thanks @Seeraeuber that looks good. Would you mind squashing everything in one commit just so that it appears neatly in the history please? I will then merge it. Cheers!

**Comment by Seeraeuber** [comment]
Hello @nickbnf, I hope I finally managed to create one single merge...
Could you please review commit d0c28a1 ?

**Comment by gin-ahirsch** [comment]
Didn't seem to work. If you used my command that's probably because it looks like your master branch also has these changes, so `git reset --soft master` referred to *your* updated master-branch, whereas my intention was to refer to the old one.
Try `git reset --soft 5abdd94b85d92e98e166cf3d8badbf111aa7d313 && git commit` (that commit id is the old master). Note that you'll need to use `git push --force-with-lease` to push changes in history.

**Comment by Seeraeuber** [comment]
@gin-ahirsch Thank you so much for the help - looks like everything is now one, neat commit as requested by @nickbnf!

**Pull request merged**
