### PR TITLE
Moving using up/down keys 

### PR DESCRIPTION
**Pull request by Pac72**
These changes:
- allow moving in AbstractLogView subclasses using key up and key down
- keep log file in sync with the search pane even when moving with the keyboard

### CODE REVIEW

**Comment by Pac72** [comment]
Hi @nickbnf, any comment on this pull request?

**Comment by variar** [comment]
As it is now this pull request is easier to apply to my branch. I suggest adapting changes to glogg/master branch, because it seems that a lot of proposed chages are irrelevant to the subject (moving with up/down keys).

**Comment by Pac72** [comment]
Could it be because the pull request is exactly 15 month old? ;-)
I'll have a look at it.

**Comment by Pac72** [comment]
@variar, I'm closing this one in favor of the new pull request #134, which applies cleanly on upstream/master

**Pull request closed without merging**
